quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.acquisition-timeout=PT5S
monitoring.alert.email=alert@mail.com
monitoring.http.timeout-seconds=5
check.services.job.every=10s

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:monitoring_test_db;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.check.services.job.every=1s
%test.monitoring.http.timeout-seconds=3
