#Database options
quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.acquisition-timeout=PT5S
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=YOUR_POSTGRES_USERNAME
quarkus.datasource.password=YOUR_POSTGRES_PASSWORD
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/YOUR_DB_NAME
quarkus.hibernate-orm.database.generation=update

#Email notifications options
monitoring.alert.email=alert@mail.com
monitoring.http.timeout-seconds=5
quarkus.mailer.host=your-provider.com
quarkus.mailer.port=587
quarkus.mailer.username=your-app-email@domain.com
quarkus.mailer.password=YOUR_SMTP_APP_PASSWORD
quarkus.mailer.tls=REQUIRED

#Scheduler options
check.services.job.every=10s

#Log/Docs options
quarkus.swagger-ui.extension-embedded-with-quarkus=true
quarkus.log.console.level=INFO
quarkus.log.category."ru.bicev".level=DEBUG

#Test options
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:monitoring_test_db;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.check.services.job.every=1s
%test.monitoring.http.timeout-seconds=3
